### ISSUE TITLE
Resource leak while building the image from source in a container environment

### ISSUE THREAD

**Issue by sbose78** [bf2fc6cc711aee1a0c2a/srs-fleet-manager#225]
1. "Too many open files"
2. High CPU usage, see https://github.com/Apicurio/apicurio-registry/issues/2100

Full log https://gist.github.com/sbose78/7dd640ecb310a84d7bd103d962d9eaac

```
[ERROR] /workspace/core/src/test/java/org/bf2/srs/fleetmanager/execution/manager/TaskManagerTest.java:[26,10] cannot access io.quarkus
[ERROR]   /root/.m2/repository/org/apache/maven/maven-embedder/3.8.1/maven-embedder-3.8.1.jar: Too many open files
```

Used the Dockerfile on https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/pull/223 . This works on my laptop of course :)

### Steps to reproduce

Following are the steps to reproduce https://github.com/Apicurio/apicurio-registry/issues/2100

1. Install OpenShift Pipelines in an OpenShift 4.9 cluster
2. Create a Pipeline definition to build an image from a Dockerfile. I've used my branch with the Dockerfile https://github.com/bf2fc6cc711aee1a0c2a/srs-fleet-manager/pull/223 

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: appstudio-dockerfile-builder
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: main
      description: Git Revision
      name: revision
      type: string
    - description: Output Image
      name: output-image
      type: string
    - default: .
      description: Context
      name: context
      type: string
    - default: Dockerfile
      description: Relative path to the Dockerfile
      name: dockerfile
      type: string
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build-container
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - clone-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: show-summary
      params:
        - name: SCRIPT
          value: |
            #!/usr/bin/env bash
            echo  
            echo Build Summary
            echo "Build for git reposisory: $(params.git-url)" 
            echo "Generated Image is in : $(params.output-image)"  
            echo 
            echo "Environment" 
            oc get pipelines 
            echo 
            echo End Summary  
      runAfter:
        - build-container
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
  workspaces:
    - name: workspace
```

3. Start the pipeline

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
  generateName: doesntmatter-
  labels:
    tekton.dev/pipeline: appstudio-dockerfile-builder
spec:
  params:
    - name: git-url
      value: 'https://github.com/sbose78/apicurio-registry'
    - name: revision
      value: build-and-deploy
    - name: output-image
      value: docker.io/sbose78/foobar
    - name: context
      value: .
    - name: dockerfile
      value: Dockerfile
  pipelineRef:
    name: appstudio-dockerfile-builder
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
        status: {}
```

4. If I used the good old buildconfig :

![image](https://user-images.githubusercontent.com/545280/145427940-cd04133d-3409-451d-be0b-416958e76b61.png)
