### ISSUE TITLE
Add async parameter to creation of registry

### ISSUE THREAD

**Issue by wtrocki** [bf2fc6cc711aee1a0c2a/srs-fleet-manager#53]
Same pattern as in kafka (API should be supporting only async for the moment) 
```
name: async          
description: Perform the action in an asynchronous manner          
schema:            
    type: boolean          
    required: true
```
